# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getcompactptr <- function(filename, variant_subset, sample_subset, xim, pvar = NULL, raw_sample_ct = NULL) {
    .Call('_pgenlibr_getcompactptr', PACKAGE = 'pgenlibr', filename, variant_subset, sample_subset, xim, pvar, raw_sample_ct)
}

NewPgen <- function(filename, pvar = NULL, raw_sample_ct = NULL, sample_subset = NULL) {
    .Call('_pgenlibr_NewPgen', PACKAGE = 'pgenlibr', filename, pvar, raw_sample_ct, sample_subset)
}

GetRawSampleCt <- function(pgen) {
    .Call('_pgenlibr_GetRawSampleCt', PACKAGE = 'pgenlibr', pgen)
}

GetVariantCt <- function(pvar_or_pgen) {
    .Call('_pgenlibr_GetVariantCt', PACKAGE = 'pgenlibr', pvar_or_pgen)
}

GetAlleleCt <- function(pvar_or_pgen, variant_num) {
    .Call('_pgenlibr_GetAlleleCt', PACKAGE = 'pgenlibr', pvar_or_pgen, variant_num)
}

GetMaxAlleleCt <- function(pvar_or_pgen) {
    .Call('_pgenlibr_GetMaxAlleleCt', PACKAGE = 'pgenlibr', pvar_or_pgen)
}

HardcallPhasePresent <- function(pgen) {
    .Call('_pgenlibr_HardcallPhasePresent', PACKAGE = 'pgenlibr', pgen)
}

Buf <- function(pgen) {
    .Call('_pgenlibr_Buf', PACKAGE = 'pgenlibr', pgen)
}

AlleleCodeBuf <- function(pgen) {
    .Call('_pgenlibr_AlleleCodeBuf', PACKAGE = 'pgenlibr', pgen)
}

IntBuf <- function(pgen) {
    .Call('_pgenlibr_IntBuf', PACKAGE = 'pgenlibr', pgen)
}

IntAlleleCodeBuf <- function(pgen) {
    .Call('_pgenlibr_IntAlleleCodeBuf', PACKAGE = 'pgenlibr', pgen)
}

BoolBuf <- function(pgen) {
    .Call('_pgenlibr_BoolBuf', PACKAGE = 'pgenlibr', pgen)
}

ReadHardcalls <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call('_pgenlibr_ReadHardcalls', PACKAGE = 'pgenlibr', pgen, buf, variant_num, allele_num))
}

Read <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call('_pgenlibr_Read', PACKAGE = 'pgenlibr', pgen, buf, variant_num, allele_num))
}

ReadAlleles <- function(pgen, acbuf, variant_num, phasepresent_buf = NULL) {
    invisible(.Call('_pgenlibr_ReadAlleles', PACKAGE = 'pgenlibr', pgen, acbuf, variant_num, phasepresent_buf))
}

ReadIntList <- function(pgen, variant_subset) {
    .Call('_pgenlibr_ReadIntList', PACKAGE = 'pgenlibr', pgen, variant_subset)
}

ReadList <- function(pgen, variant_subset, meanimpute = FALSE) {
    .Call('_pgenlibr_ReadList', PACKAGE = 'pgenlibr', pgen, variant_subset, meanimpute)
}

VariantScores <- function(pgen, weights, variant_subset = NULL) {
    .Call('_pgenlibr_VariantScores', PACKAGE = 'pgenlibr', pgen, weights, variant_subset)
}

ClosePgen <- function(pgen) {
    invisible(.Call('_pgenlibr_ClosePgen', PACKAGE = 'pgenlibr', pgen))
}

NewPvar <- function(filename) {
    .Call('_pgenlibr_NewPvar', PACKAGE = 'pgenlibr', filename)
}

GetVariantId <- function(pvar, variant_num) {
    .Call('_pgenlibr_GetVariantId', PACKAGE = 'pgenlibr', pvar, variant_num)
}

GetAlleleCode <- function(pvar, variant_num, allele_num) {
    .Call('_pgenlibr_GetAlleleCode', PACKAGE = 'pgenlibr', pvar, variant_num, allele_num)
}

ClosePvar <- function(pvar) {
    invisible(.Call('_pgenlibr_ClosePvar', PACKAGE = 'pgenlibr', pvar))
}

