# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NewDense <- function(pgen, variant_subset, meanimp) {
    .Call(`_pgenlibr_NewDense`, pgen, variant_subset, meanimp)
}

DenseTransMultv <- function(mat, v) {
    .Call(`_pgenlibr_DenseTransMultv`, mat, v)
}

DenseMultv <- function(mat, v) {
    .Call(`_pgenlibr_DenseMultv`, mat, v)
}

SparseTest123 <- function(mat, y, group, lambda_seq) {
    .Call(`_pgenlibr_SparseTest123`, mat, y, group, lambda_seq)
}

NewResponseObj <- function(y, family, status = NULL, offset = NULL) {
    .Call(`_pgenlibr_NewResponseObj`, y, family, status, offset)
}

NewProxObj <- function(ni, group) {
    .Call(`_pgenlibr_NewProxObj`, ni, group)
}

FitGroupLasso <- function(mat, prox, response, lambda_seq) {
    .Call(`_pgenlibr_FitGroupLasso`, mat, prox, response, lambda_seq)
}

ComputeLambdaMax <- function(mat, response, group) {
    .Call(`_pgenlibr_ComputeLambdaMax`, mat, response, group)
}

match_sorted_snp <- function(chr, pos, refpos, refcumu) {
    .Call(`_pgenlibr_match_sorted_snp`, chr, pos, refpos, refcumu)
}

getcompactptr <- function(filename, variant_subset, sample_subset, xim, pvar = NULL, raw_sample_ct = NULL) {
    .Call(`_pgenlibr_getcompactptr`, filename, variant_subset, sample_subset, xim, pvar, raw_sample_ct)
}

getcompactptrfromPgen <- function(pgen, variant_subset, xim, nsample) {
    .Call(`_pgenlibr_getcompactptrfromPgen`, pgen, variant_subset, xim, nsample)
}

NewPgen <- function(filename, pvar = NULL, raw_sample_ct = NULL, sample_subset = NULL) {
    .Call(`_pgenlibr_NewPgen`, filename, pvar, raw_sample_ct, sample_subset)
}

GetRawSampleCt <- function(pgen) {
    .Call(`_pgenlibr_GetRawSampleCt`, pgen)
}

GetVariantCt <- function(pvar_or_pgen) {
    .Call(`_pgenlibr_GetVariantCt`, pvar_or_pgen)
}

GetAlleleCt <- function(pvar_or_pgen, variant_num) {
    .Call(`_pgenlibr_GetAlleleCt`, pvar_or_pgen, variant_num)
}

GetMaxAlleleCt <- function(pvar_or_pgen) {
    .Call(`_pgenlibr_GetMaxAlleleCt`, pvar_or_pgen)
}

HardcallPhasePresent <- function(pgen) {
    .Call(`_pgenlibr_HardcallPhasePresent`, pgen)
}

Buf <- function(pgen) {
    .Call(`_pgenlibr_Buf`, pgen)
}

AlleleCodeBuf <- function(pgen) {
    .Call(`_pgenlibr_AlleleCodeBuf`, pgen)
}

IntBuf <- function(pgen) {
    .Call(`_pgenlibr_IntBuf`, pgen)
}

IntAlleleCodeBuf <- function(pgen) {
    .Call(`_pgenlibr_IntAlleleCodeBuf`, pgen)
}

BoolBuf <- function(pgen) {
    .Call(`_pgenlibr_BoolBuf`, pgen)
}

ReadHardcalls <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call(`_pgenlibr_ReadHardcalls`, pgen, buf, variant_num, allele_num))
}

Read <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call(`_pgenlibr_Read`, pgen, buf, variant_num, allele_num))
}

ReadAlleles <- function(pgen, acbuf, variant_num, phasepresent_buf = NULL) {
    invisible(.Call(`_pgenlibr_ReadAlleles`, pgen, acbuf, variant_num, phasepresent_buf))
}

ReadIntList <- function(pgen, variant_subset) {
    .Call(`_pgenlibr_ReadIntList`, pgen, variant_subset)
}

ReadList <- function(pgen, variant_subset, meanimpute = FALSE) {
    .Call(`_pgenlibr_ReadList`, pgen, variant_subset, meanimpute)
}

VariantScores <- function(pgen, weights, variant_subset = NULL) {
    .Call(`_pgenlibr_VariantScores`, pgen, weights, variant_subset)
}

ClosePgen <- function(pgen) {
    invisible(.Call(`_pgenlibr_ClosePgen`, pgen))
}

NewPvar <- function(filename) {
    .Call(`_pgenlibr_NewPvar`, filename)
}

GetVariantId <- function(pvar, variant_num) {
    .Call(`_pgenlibr_GetVariantId`, pvar, variant_num)
}

GetAlleleCode <- function(pvar, variant_num, allele_num) {
    .Call(`_pgenlibr_GetAlleleCode`, pvar, variant_num, allele_num)
}

ClosePvar <- function(pvar) {
    invisible(.Call(`_pgenlibr_ClosePvar`, pvar))
}

NewSparse <- function(pgen, variant_subset) {
    .Call(`_pgenlibr_NewSparse`, pgen, variant_subset)
}

TransMultv <- function(mat, v) {
    .Call(`_pgenlibr_TransMultv`, mat, v)
}

Multv <- function(mat, v) {
    .Call(`_pgenlibr_Multv`, mat, v)
}

GetSparseMeanImputation <- function(mat) {
    .Call(`_pgenlibr_GetSparseMeanImputation`, mat)
}

